version: '3.3'

services:
  # Postgres
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  web:
    build: .
    command: bash -c "python /webapps/manage.py makemigrations --noinput && python /webapps/manage.py migrate --noinput && python /webapps/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/webapps
    ports:
      - "8000:8000"
    links:
      - db
    depends_on:
      - db